spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_class_announcement_system?serverTimezone=Asia/Shanghai&useUnicode=true&characterEcoding=utf8&useSSL=false
    # the url
    username: root # the username of your MySQL
    password: admin # the username of your MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 500000
      maximum-pool-size: 100
      minimum-idle: 5 #解决mysql连接不释放问题
      connection-timeout: 30000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.criticalskill.backend.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

server:
  port: 8989 #the port number

logging:
  file:
    name:  ./backendlog/blog # search： find / -name 'blog' -type d  查看：tailf -n 5 logName.log


file-demo:
  domain: http://localhost:8989
  prefix: /p/
  file-image-path: D:\springboot-study\file-demo\file\image\
  file-thumbnail-path: D:\springboot-study\file-demo\file\thumbnail\
